name: 测试与验证

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置环境
      run: |
        chmod +x clean_trash.sh
        chmod +x scripts/test_clean_trash.sh

    - name: 运行测试
      run: ./scripts/test_clean_trash.sh